name: Mercury MIDI CI/CD

on:
  push:
    branches:
      - main # updates website only when code is pulled into main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Set version
        id: set_version
        run: |
          version=$(date +'%Y%m%d.%H%M%S')
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "{\"version\": \"$version\"}" > public/version.json

      - name: Install & Build
        run: |
          npm ci
          npm run build
          cp dist/index.html dist/404.html

      - name: Configure AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.CI_IAM_ROLE }}

      - name: Upload to S3 (versioned path)
        env:
          VERSION: ${{ steps.set_version.outputs.version }}
        run: |
          aws s3 cp dist s3://${{ secrets.APP_BUCKET }}/$VERSION --recursive

      - name: Update CloudFront origin path
        env:
          VERSION: ${{ steps.set_version.outputs.version }}
        run: |
          aws cloudfront get-distribution-config --id ${{ secrets.DISTRIBUTION_ID }} > dist-config.json
          etag=$(jq -r '.ETag' dist-config.json)
          jq '.DistributionConfig' dist-config.json > config.json
          jq --arg version "/$VERSION" '.Origins.Items[0].OriginPath = $version' config.json > updated-config.json
          aws cloudfront update-distribution \
            --id ${{ secrets.DISTRIBUTION_ID }} \
            --if-match $etag \
            --distribution-config file://updated-config.json

          # Wait for update to finish before invalidating
          while [ "$(aws cloudfront get-distribution --id ${{ secrets.DISTRIBUTION_ID }} --query 'Distribution.Status' --output text)" != "Deployed" ]; do echo "Waiting for deployment..."; sleep 5; done

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DISTRIBUTION_ID }} \
            --paths "/*"
